# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stringer < Formula
  desc "Codebase archaeology tool that mines git repos for actionable Beads issues"
  homepage "https://github.com/davetashner/stringer"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davetashner/stringer/releases/download/v1.5.0/stringer_1.5.0_darwin_amd64.tar.gz"
      sha256 "3588eb1409a73eb8a23c0e333ae9345625376277f4ace0d19af5a42ca10242c2"

      define_method(:install) do
        bin.install "stringer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davetashner/stringer/releases/download/v1.5.0/stringer_1.5.0_darwin_arm64.tar.gz"
      sha256 "bd0e6d122e01d2889779a9e21eab935311c60814d7743b0528a14fb2c5bd5219"

      define_method(:install) do
        bin.install "stringer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davetashner/stringer/releases/download/v1.5.0/stringer_1.5.0_linux_amd64.tar.gz"
      sha256 "022f7b6d60eafb8288c688f480465373a98192f5c1537a0bd73c0e8d2a5bf9c1"
      define_method(:install) do
        bin.install "stringer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davetashner/stringer/releases/download/v1.5.0/stringer_1.5.0_linux_arm64.tar.gz"
      sha256 "cc69eef1703172c58edd488b750e541362452a5a4ae8b5dc8627810c1d996cd8"
      define_method(:install) do
        bin.install "stringer"
      end
    end
  end

  test do
    system "#{bin}/stringer", "version"
  end
end
