# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stringer < Formula
  desc "Codebase archaeology tool that mines git repos for actionable Beads issues"
  homepage "https://github.com/davetashner/stringer"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davetashner/stringer/releases/download/v1.6.0/stringer_1.6.0_darwin_amd64.tar.gz"
      sha256 "9d767fc3140eeb3331f92a83ec31811636b2ea37b12e66789ad419c0bd0de936"

      define_method(:install) do
        bin.install "stringer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davetashner/stringer/releases/download/v1.6.0/stringer_1.6.0_darwin_arm64.tar.gz"
      sha256 "7a00e8478cae0b626cdb83c29e222323a7a9d63f815e8b9e87ae36638e980f17"

      define_method(:install) do
        bin.install "stringer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davetashner/stringer/releases/download/v1.6.0/stringer_1.6.0_linux_amd64.tar.gz"
      sha256 "4b397b27738192ed5ebd59bf0d82f64373d03087f9eee22c6cc788ba8c38ffa9"
      define_method(:install) do
        bin.install "stringer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davetashner/stringer/releases/download/v1.6.0/stringer_1.6.0_linux_arm64.tar.gz"
      sha256 "8ca29e956652fb3837ffaddf39fba98b422b7cf9e15a75955a1578ee9e8e773a"
      define_method(:install) do
        bin.install "stringer"
      end
    end
  end

  test do
    system "#{bin}/stringer", "version"
  end
end
